### ISSUE TITLE
Missing huta song

### ISSUE THREAD

**Issue by mamnaimieolga** [dzierzanowski/spiewnik-szant#1]
Execution: 
https://www.youtube.com/watch?v=5vs4vI_lV58

Lyrics:
hej, otrzymywanie metali z rud i złomu
to jest to, co lubię najbardziej
to jest to, co lubię najbardziej
wytapiać szkło i przetwarzać produkty szklane
praca w hucie
praca w hucie

**Comment by dzierzanowski** [comment]
Thanks for reporting the issue, @mamnaimieolga!

The song has been added in the most recent commit and included in the release tag.

**Comment by krethh** [comment]
@dzierzanowski checks should be implemented to prevent such an issue from arising in the future.

**Comment by dzierzanowski** [comment]
@krethh I will probably port the proposed song list to GH Project and implement an Action which prevents releasing with incomplete song coverage.
